// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2p1rYlKUlA0PJu_QRPVBLUjn_9PyVfW4',
    appId: '1:454880714846:web:5a34a95f4469210ae054cf',
    messagingSenderId: '454880714846',
    projectId: 'ownexpense-e8cd4',
    authDomain: 'ownexpense-e8cd4.firebaseapp.com',
    storageBucket: 'ownexpense-e8cd4.firebasestorage.app',
    measurementId: 'G-R0N2Z742NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmOq5-XD-hzrmVrGtwlJe4_aeEOAuClmw',
    appId: '1:454880714846:android:1aa245bc9fcd5332e054cf',
    messagingSenderId: '454880714846',
    projectId: 'ownexpense-e8cd4',
    storageBucket: 'ownexpense-e8cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkLYUGHQ2yQu6RIjbJGRDVvH2DGQDBiB8',
    appId: '1:454880714846:ios:f5632b0c6cf77437e054cf',
    messagingSenderId: '454880714846',
    projectId: 'ownexpense-e8cd4',
    storageBucket: 'ownexpense-e8cd4.firebasestorage.app',
    iosBundleId: 'com.example.ownexpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkLYUGHQ2yQu6RIjbJGRDVvH2DGQDBiB8',
    appId: '1:454880714846:ios:f5632b0c6cf77437e054cf',
    messagingSenderId: '454880714846',
    projectId: 'ownexpense-e8cd4',
    storageBucket: 'ownexpense-e8cd4.firebasestorage.app',
    iosBundleId: 'com.example.ownexpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2p1rYlKUlA0PJu_QRPVBLUjn_9PyVfW4',
    appId: '1:454880714846:web:3bc0a891c44386bce054cf',
    messagingSenderId: '454880714846',
    projectId: 'ownexpense-e8cd4',
    authDomain: 'ownexpense-e8cd4.firebaseapp.com',
    storageBucket: 'ownexpense-e8cd4.firebasestorage.app',
    measurementId: 'G-W9X43EHR31',
  );
}
